name: modminirc
favicon: null
layout_spectrum: 0.08380242763087153
typography_spectrum: 0.12661613104864955
title: ModMiniRC - Modular Mini Multicopters
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6602473154198378
  lightness: 0.02760086301714182
  saturation: 0.5913095511496067
  rhythmicContrast: 0.30152996396645904
purpose: []
