name: ModMiniRC
favicon: null
layout_spectrum: 0.25848
typography_spectrum: 0.44458
title: ModMiniRC - Modular Mini Multicopters
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8e6e9'
    - '#151016'
    - '#9a90ab'
    - '#5f5c77'
    - '#d3b201'
  brandStrength: 0.6602473154198378
  lightness: 0.02760086301714182
  saturation: 0.5913095511496067
  rhythmicContrast: 0.30152996396645904
purpose: []
